version: "3"

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    # you can connect with e.g.
    # psql -h localhost -p 5555 -U postgres -d db
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5558:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  # dbadmin:
  #   # accessible on http://localhost:7777
  #   depends_on:
  #     - postgres
  #   image: dpage/pgadmin4
  #   restart: always
  #   network_mode: "host"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
  #     PGADMIN_DEFAULT_PASSWORD: "admin"
  #     PGADMIN_LISTEN_PORT: 7777
